k9s:
  cluster: k8sutils.nb.no
  namespace:
    active: arc-runners
    lockFavorites: false
    favorites:
    - arc-runners
    - default
  view:
    active: po
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
