k9s:
  cluster: k8s.nb.no
  namespace:
    active: auau
    lockFavorites: false
    favorites:
    - auau
    - nbno
    - default
  view:
    active: po
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
