# Configure the format of the prompt
format = """\
        $username\
        $hostname\
        $shlvl\
        $singularity\
        $directory\
        $kubernetes\
        $git_branch\
        $git_commit\
        $git_state\
        $git_status\
        $hg_branch\
        $docker_context\
        $package\
        (↓ Toolchain version modules ↓)\
        $cmake\
        $dart\
        $dotnet\
        $elixir\
        $elm\
        $erlang\
        $golang\
        $helm\
        $java\
        $julia\
        $nim\
        $nodejs\
        $ocaml\
        $perl\
        $php\
        $purescript\
        $python\
        $ruby\
        $rust\
        $swift\
        $terraform\
        $zig\
        (↑ Toolchain version modules ↑)\
        $nix_shell\
        $conda\
        $memory_usage\
        $aws\
        $gcloud\
        $env_var\
        $crystal\
        $cmd_duration\
        $custom\
        (↑ above input line ↑)\
        $line_break\
        (↓ on input line ↓)\
        $jobs\
        $battery\
        $time\
        $status\
        $character\
    """

# Timeout for starship to scan files (in milliseconds)
scan_timeout = 30

# Add a new line before the start of the prompt
add_newline = true

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[gcloud]
disabled = true

[git_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[helm]
#disabled = false
format = "via [$symbol$version]($style) "
symbol = "⎈ "
style = "bold white"

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[kubernetes]
disabled = false
symbol = "☸ "
format = '[$symbol$context( \($namespace\))]($style) '
style = "cyan bold"

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "
disabled = false
impure_msg = 'devbox'
format = 'via [$symbol$state](bold) '

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[status]
disabled = false
format = "[$symbol$status]($style) "
symbol = "✖"
style = "bold red"

[swift]
symbol = " "

[zig]
symbol = " "
