k9s:
  cluster: k8s.stage.nb.no
  namespace:
    active: nbno
    lockFavorites: false
    favorites:
      - e2e
      - nbno
      - auau
      - default
      - nbno-test
  view:
    active: deploy
  featureGates:
    nodeShell: false
  proxy: null
