k9s:
  cluster: k8s.stage.nb.no
  namespace:
    active: auau
    lockFavorites: false
    favorites:
    - e2e
    - nbno
    - auau
    - default
    - nbno-test
  view:
    active: pods
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
