k9s:
  cluster: k8s.nb.no
  namespace:
    active: auau
    lockFavorites: false
    favorites:
      - all
      - auau
      - nbno
      - default
  view:
    active: pods
  featureGates:
    nodeShell: false
  proxy: null
