k9s:
  cluster: k8s.nb.no
  namespace:
    active: nbno
    lockFavorites: false
    favorites:
    - auau
    - nbno
    - default
  view:
    active: deploy
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
